### ISSUE TITLE
Make the persistent store configurable

### ISSUE THREAD

**Issue by milanrodriguez** [milanrodriguez/stee#9]
Add some configuration options. Something like:

```yaml
server:
  store:
    type: "integrated"
    filepath: "/var/lib/stee/stee.db"
    readonly: false
```
